---
# amazon linux specific
- name: import zabbix rpm key
  rpm_key: state=present key=http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX

- name: create yum repo 
  template: dest=/etc/yum.repos.d/zabbix.repo src=yum.repo.j2 owner=root mode=0644

- name: install zabbix agent
  yum: name=zabbix-agent state=installed

- name: start zabbix agent
  service: name=zabbix-agent state=started enabled=yes

- name: create low level scripts destination
  file: path=/etc/zabbix/scripts state=directory mode=0755

- name: install low level discovery scripts
  copy: src={{ item }} dest=/etc/zabbix/scripts/{{ item }} mode=0755
  with_items:
    - discover_hdd.sh 

- name: zabbix agent configuration
  template: dest=/etc/zabbix/zabbix_agentd.conf src=zabbix_agentd.conf.j2
  notify:
    - restart zabbix agent
